services:
  experiment-tracking:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - mlflow-artifacts:/mlruns

  train-deploy:
    build: ./l1-train-and-deploy
    profiles: ["training"]
    environment:
      - MLFLOW_TRACKING_URI=http://experiment-tracking:5000
      - PREFECT_API_URL=  # leeg = tijdelijke lokale server
    volumes:
      - ./data:/data
      - mlflow-artifacts:/mlruns
    depends_on:
      - experiment-tracking

volumes:
  mlflow-artifacts: