apiVersion: 1

datasources:
  - name: PostgreSQL-Metrics
    type: postgres
    access: proxy
    url: database:5432
    user: admin
    secureJsonData:
      password: admin
    database: metrics
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
    isDefault: true
    editable: true
